# Generated by Django 5.2.7 on 2025-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('duration_options', models.CharField(default='1day,1month,3months', max_length=100)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('certifications', models.TextField(blank=True, max_length=300)),
                ('image', models.URLField(blank=True)),
                ('services', models.ManyToManyField(related_name='caregivers', to='main_app.service')),
            ],
        ),
    ]
