# Generated by Django 5.2.7 on 2025-11-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='imageURL',
            field=models.TextField(default='https://img.freepik.com/premium-vector/default-avatar-profile-icon-social-media-user-image-gray-avatar-icon-blank-profile-silhouette-vector-illustration_561158-3407.jpg', max_length=500),
        ),
    ]
