# Generated by Django 5.2.7 on 2025-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_caregiver_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_options',
            field=models.CharField(default='1day,1month,3months', max_length=500),
        ),
    ]
